### ISSUE TITLE
многопоточная закачка

### ISSUE THREAD

**Issue by Zhambul** [LeagueOfDevelopers/Movie-Extended#81]

**Comment by Sovent** [comment]
Это что значит?

**Comment by Zhambul** [comment]
нельзя нескольким клиентам одновременно закачивать один файл с бд

**Comment by IPRIT** [comment]
Файл качается из бд?

**Comment by Sovent** [comment]
Что значит "нельзя"? В чём выражается неудача?

**Comment by Zhambul** [comment]
ну только один поток на серваке который отдает файл. (могу дико ошибаться)

**Comment by Sovent** [comment]
Вы как это выяснили?

**Comment by Zhambul** [comment]
The process cannot access the file 'D:\home\site\wwwroot\AudioTrack\77.mp3' because it is being used by another process.

**Comment by Zhambul** [comment]
Если открыть ссылку в двух вкоадках movieextended1.azurewebsites.net/api/File/Get/43

**Comment by Sovent** [comment]
Это не имеет отношения к многопоточности, это файловая система выделывается

**Comment by Sovent** [comment]
Нужно перепроверить, что файл открывается только для чтения
